version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:13
    container_name: market_intelligence_db
    environment:
      POSTGRES_DB: market_intelligence
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market_intelligence_network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: market_intelligence_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - market_intelligence_network

  # 后端 API 服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market_intelligence_backend
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/market_intelligence
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - market_intelligence_network
    restart: unless-stopped

  # 前端应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market_intelligence_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - market_intelligence_network
    restart: unless-stopped

  # Celery 工作队列
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market_intelligence_celery
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/market_intelligence
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
      - backend
    volumes:
      - ./backend:/app
    networks:
      - market_intelligence_network
    restart: unless-stopped

  # Celery Beat 调度器
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market_intelligence_celery_beat
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/market_intelligence
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
      - backend
    volumes:
      - ./backend:/app
    networks:
      - market_intelligence_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  market_intelligence_network:
    driver: bridge 